travis:
  secure:
    BINSTAR_TOKEN: nWV1nr/Z7x+Iw3r8SRPxRtV0lyGJN5Xzl9sgZAd9kfAU3lsgN6lPOImABm92PeUHUev1lMfPoLsjyB/nFLSi/UVQ7XhphhvFjYflVxc+9WyhgBfH/WoIZgNTHdqNYU8OGCEYyisCojmzdsbcCeXsiW0CMHp4XvV5Rb3scX9rYB7TBkNt11ec9N5nalXSoJrAGDsjgZoHE6O29xqC5T1qOrg0w72FptrgyqWF+9vFZNl0mzwSJDSgsP9kisnNaCiW10id4D4e33hsELch9mhITfxwBTYX8b/HiLjEQfiVRAX9CB90lvvANBhSvWrUeslDktnxbbrbMGa/siQrmnjLeFqxON7l827No+TbLE68AJNMaMBzK1yNuHfLxm8fVabBdxStba5vCULtMQufgdjrpXPHi79ohcDdCWfF5VIPu31Yn0oLkEXX8ZGuZMBo3i/iSeM4a6chQ1Y6W2LFYaqJbi3PvV/sm9SqW6et0Sc0NSjoHeDY/JoPPWqTOEqT54ZOl6b5UG7uTNXvJZwSBg/8kclH5z9f9Q6mV2h4H2gtccp/9wmciqy9LkfGf4oBhHzdUZMEA8CVABmqjvBOgbZK+ceaif2rhD3Vad79sWnObaXaGiuWOMWyYGz1FqkuV3LSoUdsLX6gPzaRht+5LhGsw5nuzRTCp4HHHQAN78jOlAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
