travis:
  secure:
    BINSTAR_TOKEN: xJD474AzyfdLm5X7WRYp7zakhFpUksJglDtxcBiKRooNdVUTfHNvU/6jvUsO0EBVyUSCYo5O+G9+wKNfyfIQU0a4H9F6SkbfKrJSR5ZlKtP4GPJtjNphqksm5Wg+Gpp9gDCqMwf5rGGyEkIe/X2J2bvB16Se8My6uep5/cUpQ7KNbGFkJQrB3M/KCmuDFayIro0feKb9Vb4oROWtmBfbkKUOQDKktK62uPAF/Z3/ITxTMHRxyReVsRpIN/yC4e1fmZSw4lcDuQ276eoCjs31Q4iQqG+cp3rDuZh+gvFRpRglsy4EYfm6Zamol12/Ol0cUMrgTr80Tzy5aHDUfl6SS+TUBD5VlrB1uKyReY0AC+LHUSUiWv/KosJ+UP8W0pPMDFF8nQXrLJOhjYbSrL0VsTg3w3BDA0DwKJ9NMT9rn/ewaQgLurQAHPO/eMqJyM1NyQ9zB8tmYc4JEbW/EGHwj26ZFL6s3rEaVU2zDhX6Zq09elvkw9mq3qZ7QAFE9vN92iB5DaeO1Pu80Nl3H0odKW5Ex01Hdnf5irpB+a92mbcYwB0of1LdeAD7QvUnLHBJykjGV4wDBmC0n0yx4oVvHPsG0qOgduCSvxlXsBj6zFaqxYdRJ4VzTwnk1asgkzeEvQdhmRRCP2D54DYX8NhfYnKiKmsvnvfl5exJbiqPctM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
